# Generated by Django 5.2 on 2025-05-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the supplier company or individual.', max_length=200, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person at the supplier.', max_length=150, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address for the supplier.', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number for the supplier.', max_length=30, null=True)),
                ('address', models.TextField(blank=True, help_text='Physical or mailing address of the supplier.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any relevant notes about the supplier.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
