# Generated by Django 5.2 on 2025-05-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category (e.g., Furniture, Linens, AV Equipment).', max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent category for creating hierarchies.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Clear, descriptive name (e.g., 'White Folding Chair', '6ft Rectangular Table').", max_length=200)),
                ('description', models.TextField(blank=True, help_text='More detailed notes about the item.', null=True)),
                ('sku', models.CharField(blank=True, editable=False, help_text='System-generated unique Stock Keeping Unit.', max_length=50, unique=True)),
                ('storage_location', models.CharField(blank=True, help_text='Physical storage location (e.g., Warehouse A, Shelf B-3).', max_length=200)),
                ('initial_quantity', models.PositiveIntegerField(default=0, help_text='Total number of this specific item owned.')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimension_unit', models.CharField(choices=[('CM', 'Centimeters'), ('IN', 'Inches')], default='CM', help_text='Units for the dimensions provided.', max_length=2)),
                ('image1', models.ImageField(help_text='Primary image of the item.', upload_to='item_images/')),
                ('image2', models.ImageField(blank=True, help_text='Optional second image of the item.', null=True, upload_to='item_images/')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of acquiring a single unit of this item (for valuation).', max_digits=10, null=True)),
                ('rent_price_per_day', models.DecimalField(decimal_places=2, help_text='Daily rental charge for a single unit of this item.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category this item belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.category')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier this item was purchased from (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_items', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
