# Generated by Django 5.2 on 2025-05-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_length_item_depth_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_source',
            field=models.CharField(choices=[('OWNED', 'Owned by Company'), ('CLIENT_SUPPLIED', 'Supplied by Client for Event')], default='OWNED', help_text='Indicates the source or ownership of the item.', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total number of this specific item owned or received from client.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of acquiring a single unit of this item (for valuation, N/A for client-supplied).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rent_price_per_day',
            field=models.DecimalField(decimal_places=2, help_text='Daily rental charge for a single unit of this item (N/A for client-supplied).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier this item was purchased from (optional, N/A for client-supplied).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_items', to='suppliers.supplier'),
        ),
    ]
