# Generated by Django 5.2.4 on 2025-07-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_item_source_alter_item_initial_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dimension_unit',
            field=models.CharField(choices=[('CM', 'Centimeters'), ('IN', 'Inches'), ('MM', 'Millimeters'), ('M', 'Meters'), ('DM', 'Diameters')], default='CM', help_text='Units for the dimensions provided (Depth x Width x Height).', max_length=5),
        ),
    ]
