# Generated by Django 5.2.4 on 2025-07-16 10:50

import django.db.models.deletion
import request_quote.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_itemimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('event_start_date', models.DateTimeField()),
                ('setup_installation_datetime', models.DateTimeField()),
                ('event_end_date', models.DateTimeField()),
                ('setup_removal_datetime', models.DateTimeField()),
                ('event_title', models.CharField(max_length=255)),
                ('subcontractors', models.CharField(blank=True, max_length=255)),
                ('delivery_note_signed_from', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('reference_number', models.CharField(default=request_quote.models.generate_reference_number, max_length=50, unique=True)),
                ('project_manager_notes', models.TextField(blank=True)),
                ('project_manager', models.ForeignKey(blank=True, help_text='User assigned as Project Manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='The number of units of this item booked.')),
                ('booking', models.ForeignKey(help_text='The quote request this item is linked to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='request_quote.quoterequest')),
                ('item', models.ForeignKey(help_text='The specific inventory item booked.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Quote Request Item',
                'verbose_name_plural': 'Quote Request Items',
                'unique_together': {('booking', 'item')},
            },
        ),
    ]
