# Generated by Django 5.2.4 on 2025-07-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_email_alter_client_phone'),
        ('request_quote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='client_name',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='client',
            field=models.ForeignKey(blank=True, help_text='The client associated with this quote.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='clients.client'),
        ),
    ]
