# Generated by Django 5.2 on 2025-05-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project_manager_name',
            field=models.CharField(blank=True, help_text='Name of the assigned Project Manager.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='subcontractor_name',
            field=models.CharField(blank=True, help_text='Name of the subcontractor, if any.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='project_manager_name',
            field=models.CharField(blank=True, help_text='Name of the assigned Project Manager.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='subcontractor_name',
            field=models.CharField(blank=True, help_text='Name of the subcontractor, if any.', max_length=200, null=True),
        ),
    ]
