# Generated by Django 5.2 on 2025-05-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_event_project_manager_name_event_subcontractor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='delivery_location',
            field=models.CharField(blank=True, help_text='Optional delivery location for the rental items.', max_length=255, null=True),
        ),
    ]
