# Generated by Django 5.2 on 2025-05-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rental_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='Default Event Name', help_text='The official name or title of the event.', max_length=255),
            preserve_default=False,
        ),
    ]
