# Generated by Django 5.2 on 2025-06-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_event_event_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'created_at'], 'verbose_name': 'Event / Logistics Booking', 'verbose_name_plural': 'Event / Logistics Bookings'},
        ),
        migrations.AddField(
            model_name='event',
            name='delivery_address_override',
            field=models.TextField(blank=True, help_text='Specific delivery address for logistics if different from main Event Location (e.g. event_location).', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='delivery_contact_details',
            field=models.TextField(blank=True, help_text='Contact name and phone for the delivery at the event site.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_of_goods',
            field=models.TextField(blank=True, help_text='Description of goods being transported for a logistics service (e.g., quantity, type, special handling).', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_logistics_only_service',
            field=models.BooleanField(default=False, help_text='Check if this booking is primarily for a logistics/transport service only.'),
        ),
        migrations.AddField(
            model_name='event',
            name='pickup_address',
            field=models.TextField(blank=True, help_text='Full address for picking up goods from the client.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pickup_contact_details',
            field=models.TextField(blank=True, help_text='Contact name and phone for the pickup location.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='return_delivery_address',
            field=models.TextField(blank=True, help_text="Final return address for the goods (e.g., client's warehouse).", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='return_delivery_contact_details',
            field=models.TextField(blank=True, help_text='Contact name and phone for the final return delivery.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='return_pickup_address',
            field=models.TextField(blank=True, help_text='Address for picking up goods from the event site for return (usually same as Event Location or Delivery Address Override).', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='return_pickup_contact_details',
            field=models.TextField(blank=True, help_text='Contact name and phone for pickup from the event site.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(help_text='Specific address or location description for the event or primary delivery site.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(help_text='The official name or title of the event/service.', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', help_text='Current status of the event booking/logistics task.', max_length=10),
        ),
    ]
