# Generated by Django 5.2.4 on 2025-07-17 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_event_options_event_delivery_address_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project_manager',
            field=models.ForeignKey(blank=True, help_text='User assigned as Project Manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_as_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rental',
            name='project_manager',
            field=models.ForeignKey(blank=True, help_text='User assigned as Project Manager.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_as_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
